import type {
  NormalizedEvent,
  WorkflowSuggestion,
  Integration,
  DashboardMetrics,
  EventVolumeData,
  FocusStats,
} from "./types"

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000"

async function fetchJson<T>(url: string, options?: RequestInit): Promise<T> {
  let token: string | null = null
  if (typeof window !== "undefined") {
    token = localStorage.getItem("auth_token")
  }

  const res = await fetch(url, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(options?.headers || {}),
    },
  })
  if (!res.ok) {
    throw new Error(`API error: ${res.statusText} (${res.status})`)
  }
  const body = await res.json()
  if (!body.success) {
    throw new Error(body.error || "API call failed")
  }
  return body.data as T
}

export async function fetchDashboardMetrics(): Promise<DashboardMetrics> {
  try {
    const stats = await fetchJson<{
      total: number
      bySeverity: Record<string, number>
      bySource: Record<string, number>
      byStatus: Record<string, number>
    }>(`${API_BASE_URL}/api/events/stats`)

    const criticalAlerts = stats.bySeverity.critical ?? 0
    const openAnomalies = (stats.bySeverity.high ?? 0) + (stats.bySeverity.critical ?? 0)

    // Calculate events today
    const events = await fetchJson<NormalizedEvent[]>(`${API_BASE_URL}/api/events/recent`)
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    const eventsToday = events.filter(e => new Date(e.timestamp) >= today).length

    return {
      eventsToday: eventsToday || stats.total,
      activePipelines: stats.bySource.github ?? 3, // fallback default
      openAnomalies,
      criticalAlerts,
    }
  } catch (err) {
    console.error("fetchDashboardMetrics failed, falling back to mock", err)
    return {
      eventsToday: 1247,
      activePipelines: 18,
      openAnomalies: 7,
      criticalAlerts: 2,
    }
  }
}

export async function fetchFocusStats(): Promise<FocusStats> {
  try {
    const stats = await fetchJson<{
      total: number
      bySeverity: Record<string, number>
      bySource: Record<string, number>
      byStatus: Record<string, number>
    }>(`${API_BASE_URL}/api/events/stats`)

    return {
      pendingReview: stats.byStatus.open ?? 0,
      criticalOpen: stats.bySeverity.critical ?? 0,
      unresolvedAnomalies: (stats.bySeverity.high ?? 0) + (stats.bySeverity.critical ?? 0),
    }
  } catch (err) {
    console.error("fetchFocusStats failed, falling back to mock", err)
    return {
      pendingReview: 4,
      criticalOpen: 2,
      unresolvedAnomalies: 7,
    }
  }
}

export async function fetchEvents(params?: {
  page?: number
  limit?: number
  source?: string
  severity?: string
  status?: string
}): Promise<{ data: NormalizedEvent[]; total: number }> {
  try {
    const query = new URLSearchParams()
    if (params?.page) query.append("page", String(params.page))
    if (params?.limit) query.append("limit", String(params.limit))
    if (params?.source && params.source !== "all") query.append("source", params.source)
    if (params?.severity && params.severity !== "all") query.append("severity", params.severity)
    if (params?.status && params.status !== "all") query.append("status", params.status)

    const url = `${API_BASE_URL}/api/events?${query.toString()}`
    const res = await fetch(url)
    if (!res.ok) throw new Error("Failed to fetch events")
    const body = await res.json()
    return {
      data: body.data,
      total: body.pagination.total,
    }
  } catch (err) {
    console.error("fetchEvents failed", err)
    return { data: [], total: 0 }
  }
}

export async function fetchRecentEvents(): Promise<NormalizedEvent[]> {
  try {
    return await fetchJson<NormalizedEvent[]>(`${API_BASE_URL}/api/events/recent`)
  } catch (err) {
    console.error("fetchRecentEvents failed", err)
    return []
  }
}

export async function fetchWorkflows(): Promise<WorkflowSuggestion[]> {
  try {
    const data = await fetchJson<any[]>(`${API_BASE_URL}/api/workflow/latest?limit=15`)
    return data.map((item) => ({
      id: item.id,
      anomalyId: item.id,
      title: item.workflow?.title || `Optimize workflow: ${item.metric}`,
      description: item.workflow?.problem || item.rootCause || "Workflow recommendation",
      steps: (item.workflow?.actionPlan || []).map((label: string, idx: number) => ({
        label,
        description: `Action step generated by optimization model.`,
      })),
      createdAt: item.processedAt || item.receivedAt || new Date().toISOString(),
      svg: item.svg,
    }))
  } catch (err) {
    console.error("fetchWorkflows failed", err)
    return []
  }
}

export async function fetchIntegrations(): Promise<Integration[]> {
  try {
    return await fetchJson<Integration[]>(`${API_BASE_URL}/api/integrations`)
  } catch (err) {
    console.error("fetchIntegrations failed", err)
    return []
  }
}

export async function triggerManualPoll(source: string): Promise<Integration> {
  return await fetchJson<Integration>(`${API_BASE_URL}/api/integrations/poll/${source}`, {
    method: "POST",
  })
}

export async function executeWorkflow(id: string): Promise<any> {
  return await fetchJson<any>(`${API_BASE_URL}/api/workflow/${id}/execute`, {
    method: "POST",
  })
}
