import type {
  NormalizedEvent,
  AnomalyPayload,
  WorkflowSuggestion,
  Integration,
  DashboardMetrics,
  EventVolumeData,
  FocusStats,
} from "./types"

export const mockMetrics: DashboardMetrics = {
  eventsToday: 1247,
  activePipelines: 18,
  openAnomalies: 7,
  criticalAlerts: 2,
}

export const mockEventVolume: EventVolumeData[] = [
  { date: "Jan", events: 980 },
  { date: "Feb", events: 1120 },
  { date: "Mar", events: 1340 },
  { date: "Apr", events: 1090 },
  { date: "May", events: 1560 },
  { date: "Jun", events: 1780 },
  { date: "Jul", events: 1247 },
]

export const mockFocusStats: FocusStats = {
  pendingReview: 4,
  criticalOpen: 2,
  unresolvedAnomalies: 7,
}

export const mockEvents: NormalizedEvent[] = [
  {
    id: "evt-001",
    source: "github",
    eventType: "push",
    resource: "flowsense/backend",
    timestamp: "2026-07-04T10:23:00Z",
    metric: "commit_frequency",
    value: 14,
    severity: "low",
    status: "open",
    tags: ["ci", "main-branch"],
  },
  {
    id: "evt-002",
    source: "jira",
    eventType: "issue_created",
    resource: "FLOW-482",
    timestamp: "2026-07-04T09:45:00Z",
    metric: "ticket_velocity",
    value: 3,
    severity: "medium",
    status: "open",
    tags: ["sprint-12", "backend"],
  },
  {
    id: "evt-003",
    source: "github",
    eventType: "pr_merged",
    resource: "flowsense/frontend",
    timestamp: "2026-07-04T08:30:00Z",
    metric: "merge_rate",
    value: 0.85,
    severity: "low",
    status: "resolved",
    tags: ["feature", "ui"],
  },
  {
    id: "evt-004",
    source: "notion",
    eventType: "page_updated",
    resource: "Sprint 12 Retro",
    timestamp: "2026-07-04T07:15:00Z",
    metric: "doc_activity",
    value: 8,
    severity: "low",
    status: "open",
    tags: ["docs", "retro"],
  },
  {
    id: "evt-005",
    source: "github",
    eventType: "workflow_failed",
    resource: "flowsense/api",
    timestamp: "2026-07-04T06:50:00Z",
    metric: "ci_failure_rate",
    value: 0.32,
    severity: "high",
    status: "open",
    tags: ["ci", "failure"],
  },
  {
    id: "evt-006",
    source: "jira",
    eventType: "sprint_completed",
    resource: "Sprint 11",
    timestamp: "2026-07-03T18:00:00Z",
    metric: "sprint_completion",
    value: 0.78,
    severity: "medium",
    status: "resolved",
    tags: ["sprint-11", "completed"],
  },
  {
    id: "evt-007",
    source: "github",
    eventType: "release_published",
    resource: "flowsense/backend v2.4.0",
    timestamp: "2026-07-03T14:20:00Z",
    metric: "release_frequency",
    value: 1,
    severity: "low",
    status: "resolved",
    tags: ["release", "backend"],
  },
  {
    id: "evt-008",
    source: "notion",
    eventType: "database_modified",
    resource: "Roadmap Q3",
    timestamp: "2026-07-03T11:30:00Z",
    metric: "planning_activity",
    value: 5,
    severity: "low",
    status: "open",
    tags: ["planning", "q3"],
  },
]

export const mockAnomalies: AnomalyPayload[] = [
  {
    anomalyId: "anom-001",
    detectedAt: "2026-07-04T10:15:00Z",
    severity: "critical",
    status: "open",
    metric: "ci_failure_rate",
    source: "github",
    rootCause: "Flaky integration tests in auth module causing cascading CI failures across 3 pipelines.",
    businessImpact: "Blocking 4 PRs from merging. Deploy pipeline stalled for 2+ hours.",
    factors: ["Test timeout increased 3x", "Auth service dependency unreachable", "Retry storms detected"],
    urgency: "Immediate — deploy pipeline blocked",
    eventsCount: 12,
  },
  {
    anomalyId: "anom-002",
    detectedAt: "2026-07-04T08:30:00Z",
    severity: "high",
    status: "acknowledged",
    metric: "ticket_velocity",
    source: "jira",
    rootCause: "Sprint velocity dropped 40% due to unplanned scope increase mid-sprint.",
    businessImpact: "Sprint 12 at risk of missing deadline. 6 story points unstarted.",
    factors: ["3 new P1 tickets added", "2 engineers reassigned", "Estimation drift"],
    urgency: "High — sprint deadline in 3 days",
    eventsCount: 8,
  },
  {
    anomalyId: "anom-003",
    detectedAt: "2026-07-03T22:00:00Z",
    severity: "medium",
    status: "open",
    metric: "commit_frequency",
    source: "github",
    rootCause: "Unusual spike in commit frequency on main branch — possible hotfix deployment without review.",
    businessImpact: "Code review coverage dropped to 60%. Risk of unreviewed changes in production.",
    factors: ["8 direct pushes to main", "No PR associated", "After-hours activity"],
    urgency: "Review needed within 24h",
    eventsCount: 8,
  },
  {
    anomalyId: "anom-004",
    detectedAt: "2026-07-03T16:45:00Z",
    severity: "low",
    status: "resolved",
    metric: "doc_activity",
    source: "notion",
    rootCause: "Mass documentation updates triggered by quarterly review process.",
    businessImpact: "None — expected activity pattern during Q3 planning.",
    factors: ["Quarterly review cycle", "12 pages updated simultaneously"],
    urgency: "Informational",
    eventsCount: 12,
  },
  {
    anomalyId: "anom-005",
    detectedAt: "2026-07-03T12:00:00Z",
    severity: "high",
    status: "open",
    metric: "merge_rate",
    source: "github",
    rootCause: "PR merge rate dropped 55%. Multiple PRs stuck in review for 48+ hours.",
    businessImpact: "Feature delivery delayed. 5 PRs with approved reviews not merged.",
    factors: ["Reviewer bottleneck", "CI queue congestion", "Branch conflicts"],
    urgency: "Needs attention today",
    eventsCount: 5,
  },
]

export const mockWorkflows: WorkflowSuggestion[] = [
  {
    id: "wf-001",
    anomalyId: "anom-001",
    title: "CI Failure Recovery Workflow",
    description: "Automated recovery steps to unblock the deploy pipeline and prevent cascading test failures.",
    steps: [
      { label: "Quarantine flaky tests", description: "Move auth integration tests to quarantine suite" },
      { label: "Restart CI runners", description: "Flush stale runners and reset auth service mock" },
      { label: "Rerun blocked PRs", description: "Trigger fresh CI runs for the 4 stalled pull requests" },
      { label: "Add retry budget", description: "Configure 2-retry limit for integration test suite" },
    ],
    createdAt: "2026-07-04T10:16:00Z",
  },
  {
    id: "wf-002",
    anomalyId: "anom-002",
    title: "Sprint Recovery Plan",
    description: "Rebalance sprint scope and reassign work to meet the Sprint 12 deadline.",
    steps: [
      { label: "Triage new tickets", description: "Review 3 new P1s — defer non-critical items to Sprint 13" },
      { label: "Reassign capacity", description: "Pair junior devs with available senior for blocked stories" },
      { label: "Daily standup focus", description: "15-min sync focused only on blocked items" },
    ],
    createdAt: "2026-07-04T08:31:00Z",
  },
  {
    id: "wf-003",
    anomalyId: "anom-005",
    title: "PR Review Acceleration",
    description: "Clear the review backlog and prevent future bottlenecks.",
    steps: [
      { label: "Assign backup reviewers", description: "Add secondary reviewers to all PRs older than 24h" },
      { label: "Break large PRs", description: "Split the 2 largest PRs into reviewable chunks" },
      { label: "Set SLA alerts", description: "Configure alerts for PRs pending review > 4h" },
    ],
    createdAt: "2026-07-03T12:05:00Z",
  },
]

export const mockIntegrations: Integration[] = [
  {
    id: "int-001",
    source: "github",
    name: "GitHub",
    status: "connected",
    lastPollAt: "2026-07-04T10:20:00Z",
    eventsToday: 847,
    totalEvents: 24500,
  },
  {
    id: "int-002",
    source: "jira",
    name: "Jira",
    status: "connected",
    lastPollAt: "2026-07-04T10:18:00Z",
    eventsToday: 312,
    totalEvents: 8900,
  },
  {
    id: "int-003",
    source: "notion",
    name: "Notion",
    status: "connected",
    lastPollAt: "2026-07-04T10:15:00Z",
    eventsToday: 88,
    totalEvents: 3200,
  },
]

export const mockAttentionItems = [
  {
    id: "att-001",
    title: "CI pipeline blocked",
    subtitle: "flowsense/backend — 4 PRs stalled",
    tone: "danger" as const,
    value: "2h ago",
  },
  {
    id: "att-002",
    title: "Sprint velocity drop",
    subtitle: "Sprint 12 — 40% below target",
    tone: "warn" as const,
    value: "3d left",
  },
  {
    id: "att-003",
    title: "PR review backlog",
    subtitle: "5 PRs pending > 48h",
    tone: "warn" as const,
    value: "5 PRs",
  },
  {
    id: "att-004",
    title: "Notion sync healthy",
    subtitle: "Q3 Roadmap fully updated",
    tone: "neutral" as const,
    value: "OK",
  },
]
